name: Node.js integration
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  nodejs-integration:
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        python-version: ["3.10", "3.12", "3.14"]
        include:
          - os: macos-15-intel  # macOS on Intel
            python-version: "3.14"
          - os: ubuntu-24.04-arm  # Ubuntu on ARM
            python-version: "3.14"
          - os: windows-11-arm  # Windows on ARM
            python-version: "3.14"

    runs-on: ${{ matrix.os }}
    steps:
      - name: Clone gyp-next
        uses: actions/checkout@v6
        with:
          path: gyp-next
      - name: Clone nodejs/node
        uses: actions/checkout@v6
        with:
          repository: nodejs/node
          path: node
      - uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}
          allow-prereleases: true
      - name: Replace gyp in Node.js
        shell: bash
        run: |
          rm -rf node/tools/gyp
          cp -r gyp-next node/tools/gyp

      # macOS and Linux
      - name: Run configure
        if: runner.os != 'Windows'
        run: |
          cd node
          ./configure

      # Windows
      - name: Install deps
        if: runner.os == 'Windows'
        run: choco install nasm
      - name: Run configure
        if: runner.os == 'Windows'
        run: |
          cd node
          ./vcbuild.bat nobuild
