name: node-gyp integration
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  node-gyp-integration:
    strategy:
      fail-fast: false
      matrix:
        node-version: ["22"]
        os: [macos-latest, ubuntu-latest, windows-latest]
        python-version: ["3.9", "3.11", "3.13"]
        include:
          - node-version: "22"
            os: macos-13  # macOS on Intel
            python-version: "3.13"
          - node-version: "22"
            os: ubuntu-24.04-arm  # Ubuntu on ARM
            python-version: "3.13"
          - node-version: "22"
            os: windows-11-arm  # Windows on ARM
            python-version: "3.13"
    runs-on: ${{ matrix.os }}
    steps:
      - name: Clone gyp-next
        uses: actions/checkout@v5
        with:
          path: gyp-next
      - name: Clone nodejs/node-gyp
        uses: actions/checkout@v5
        with:
          repository: nodejs/node-gyp
          path: node-gyp
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          allow-prereleases: true
      - name: Install Python dependencies
        run: |
          cd gyp-next
          python -m pip install --upgrade pip
          pip install --editable .
          pip uninstall -y gyp-next
      - name: Install Node.js dependencies
        run: |
          cd node-gyp
          npm install --no-progress
      - name: Replace gyp in node-gyp
        shell: bash
        run: |
          rm -rf node-gyp/gyp
          cp -r gyp-next node-gyp/gyp
      - name: Run tests (macOS or Linux)
        if: runner.os != 'Windows'
        run: |
          cd node-gyp
          npm test --python="${pythonLocation}/python"
      - name: Run tests (Windows)
        if: runner.os == 'Windows'
        shell: pwsh
        run: |
          cd node-gyp
          npm run test --python="${env:pythonLocation}\\python.exe"
