name: node-gyp integration
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  node-gyp-integration:
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        python-version: ["3.10", "3.12", "3.14"]
        #exclude:
        #  # Windows on Python 3.14 is blocked by nodejs/node#59983
        #  - os: windows-latest
        #    python-version: "3.14"
        include:
          - os: windows-latest
            python-version: "3.14"
          - os: macos-15-intel  # macOS on Intel
            python-version: "3.14"
          - os: ubuntu-24.04-arm  # Ubuntu on ARM
            python-version: "3.14"
          - os: windows-11-arm  # Windows on ARM
            python-version: "3.14"
    runs-on: ${{ matrix.os }}
    steps:
      - name: Clone gyp-next
        uses: actions/checkout@v6
        with:
          path: gyp-next
      - name: Clone nodejs/node-gyp
        uses: actions/checkout@v6
        with:
          repository: nodejs/node-gyp
          path: node-gyp
      - uses: actions/setup-node@v6
        with:
          node-version: "lts/*"
      - name: Use Python ${{ matrix.python-version }}
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}
          allow-prereleases: true
      - name: Install Python dependencies
        run: |
          cd gyp-next
          python -m pip install --upgrade pip
          pip install --editable .
          pip uninstall -y gyp-next
      - name: Install Node.js dependencies
        run: |
          cd node-gyp
          npm install --no-progress
      - name: Replace gyp in node-gyp
        shell: bash
        run: |
          rm -rf node-gyp/gyp
          cp -r gyp-next node-gyp/gyp
      - run: echo "env:pythonLocation=${env:pythonLocation}"
      # - run: env
      - name: Run tests
        run: |
          cd node-gyp
          npm test
