# https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources

name: visual-studio
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read # to fetch code (actions/checkout)

jobs:
  visual-studio:
    strategy:
      fail-fast: false
      max-parallel: 8
      matrix:
        include:
          - os: windows-2019
            msvs-verison: 2019
          - os: windows-2022
            msvs-version: 2022
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Install Dependencies
        run: |
          npm install --no-progress
      - name: Environment Information
        run: npx envinfo
      - name: Run Node tests
        shell: pwsh
        run: |
          $pythonLocation = (Get-Command python).Source
          npm run test --python="${pythonLocation}" --msvs-version="${{ matrix.msvs-version }}"
