# https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources

name: visual-studio
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read # to fetch code (actions/checkout)

jobs:
  visual-studio:
    strategy:
      fail-fast: false
      max-parallel: 8
      matrix:
        include:
          - os: windows-2022
            msvs-version: 2022
          - os: windows-2025
            msvs-version: 2022  # Fix this when Visual Studio 2025 is released
          - os: windows-11-arm
            msvs-version: 2022  # Fix this when Visual Studio 2025 is released
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6
      - name: Use Python 3
        uses: actions/setup-python@v6
        with:
          python-version: "3.x"
      - name: Install Dependencies
        run: npm install
      # - run: echo "pythonLocation=${pythonLocation}"
      - run: echo "env:pythonLocation=${env:pythonLocation}"
      # - run: env
      - name: Run Node tests
        shell: bash # Building wasm on Windows requires using make generator, it only works in bash
        run: npm run test
